### ISSUE TITLE
Refactor log managment

### ISSUE THREAD

**Issue by catlauraherzog** [conceptsandtraining/doil#108]
- [ ] Basis-Log-System

- [x] Doil-System-Logs
 - /var/log/doil.log
 - Alle Meldungen des System
 - keine Salt-Logs und Zustandsmeldungen
 - Basismeldungen (Ich erstelle jetzt Instanz $foo)

- [ ] Instance-Logs
 - $instance/volumes/logs/doil.log
 - Systemmeldungen (Ich erstelle Instanz mit config $foo)
 - Alle Salt-Logs zu dieser Instanz (auch proxy und postfix trigger)
 - keine ILIAS spezifischen Fehlermeldungen

- [x] ILIAS-Logs
 - sind in $instance/volumes/logs
 - keine Änderungen notwendig

**Comment by daniwe4** [comment]
Bitte nicht auf die Beschreibung von oben achten. Hier wurde nur ein Logging System implementiert, welches einen Doil und einen Salt Logger implementiert.

https://github.com/conceptsandtraining/doil/pull/270

**Comment by tbongers-cat** [comment]
Die Änderungen aus #270 sind jetzt drin, können wir die Issue damit schon schließen? @daniwe4
