### ISSUE TITLE
Deletion of Instance Fails

### ISSUE THREAD

**Issue by klees** [conceptsandtraining/doil#136]
I try to delete an existing instance, but the instance won't get deleted completely. The composer directory in the ilias volume (which I filled by calling `composer install` from within the installation) is not deleted because of missing permissions.

**Comment by klees** [comment]
I think this might happen when something breaks during creation of the instance (which is what happened in my case) and `Apply access state` is not executed.

**Comment by klees** [comment]
This also happens if `Apply access state` has run.

**Comment by lauraherzog** [comment]
More or less duplicate with #145, therefore close but with reference.
