### ISSUE TITLE
doil deinstall not working

### ISSUE THREAD

**Issue by klees** [conceptsandtraining/doil#138]
When I run the command I get:

$ doil deinstall
ERROR:
	Can't find a suitable command.
	Use doil help for more information

**Comment by lauraherzog** [comment]
The command is 'doil system:deinstall`

**Comment by klees** [comment]
Ok, I see. It seems the output from `doil` a bit confusing in that regard:

```
$  doil
NAME
  doil system - manages the doil system

SYNOPSIS
  doil system:<command>

DESCRIPTION
  doil provides you with a simple way to create and manage
  development and testing environments for ILIAS. It will
  create and provision a docker container according to your
  requirements, pull the ILIAS version you want to use and even
  install it if possible. Every section and command comes with
  its own help which you can access by adding --help|-h to it.

EXAMPLE:
  doil system:proxy login

COMMANDS
  deinstall deinstalls doil
  version   shows the currently installed version 
  salt      manages the salt server
  proxy     manages the proxy server
  user      manages the doil user
```

This obv tells that `system:deinstall` is the way to go, but I skipped to the `COMMANDS` without reading it =)

Maybe the problem is this, then, and doil should tell about the sub commands (system, instance, repo) when user just types `doil`?

**Comment by lauraherzog** [comment]
If `doil` is entered without anything it'll show the base help now.
