### ISSUE TITLE
Fehler bei git pull vom host

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#142]
Führe ich einen git pull Befehl vom Host System aus, kommt es zu folgendem Fehler bei Cpt Hook:

post-merge: 
 - composer install                                                  : done
 - CI/tools/compile-skins.sh                                         : failed

failed to execute: CI/tools/compile-skins.sh

lessc: failed to create file /home/dweise/Projekte/doil/instances/tms7/volumes/ilias/Customizing/global/skin/custom/axa/skin.css
Error: EACCES EACCES: permission denied, open '/home/dweise/Projekte/doil/instances/tms7/volumes/ilias/Customizing/global/skin/custom/axa/skin.css'

**Comment by lauraherzog** [comment]
Duplicate, see #146
