### ISSUE TITLE
Can't compile skins from outside of container

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#146]
Try to git pull origin master from outside of the container. Composer install works fine but compiling skins results in following error:

post-merge: 
 - composer install                                                  : done
 - CI/tools/compile-skins.sh                                         : failed

failed to execute: CI/tools/compile-skins.sh

lessc: failed to create file /home/dweise/Projekte/doil/instances/origin/volumes/ilias/Customizing/global/skin/custom/axa/skin.css
Error: EACCES EACCES: permission denied, open '/home/dweise/Projekte/doil/instances/origin/volumes/ilias/Customizing/global/skin/custom/axa/skin.css'

**Comment by lauraherzog** [comment]
Nice idea for an improvement. Hard to implement tbh. Moved to later release and we should talk about this.

**Comment by daniwe4** [comment]
Nicht mehr relevant.
