### ISSUE TITLE
XDEBUG

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#167]
Please ensure that php-xdebug is installed inside of a container. Also, the php-ini config has to be adjust under /etc/php/<php_version>/apache2/php.ini.
Please add these lines at the end of the file:

xdebug.mode = develop,debug,profile
xdebug.discover_client_host = true
xdebug.client_port = 9000
xdebug.log = /var/log/xdebug.log
xdebug.start_with_request = trigger
xdebug.output_dir = /var/log/xprofiles"

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/253

**Comment by tbongers-cat** [comment]
Added in #253
