### ISSUE TITLE
Create instance from existing package might be faster

### ISSUE THREAD

**Issue by shecken** [conceptsandtraining/doil#185]
If i create a doil instance out of an existing package, the length of time is still about 30minutes. is there any possibility to speed this up? My hope was to create an instance within a few minutes (max 10)

**Comment by daniwe4** [comment]
Momentan wird für jede neue Instanz ein Docker-Image erzeugt. Auch bei Imports. Das nimmt die meiste Zeit in Anspruch.
Ziel ist es, in einer zukünftigen doil Version ein base-Image zu haben von dem aus die Container erzeugt werden. Das sollte dann deutlich schneller gehen.
Ich habe das Ticket in den Milestone Feature Release geschoben.

**Comment by daniwe4** [comment]
Hi @shecken ,

mit https://github.com/conceptsandtraining/doil/pull/329 werden neue Images aus einem base image gebuat. Das sorgt dafür, dass ein import einer leeren cate master Instanz ca. 12 min. dauert.
Die größten Zeitfresser sind somit der Autoinstall und das kompilieren der Skins.
An beiden kann ich momentan nichts machen. Ich hoffe, dass das kompilieren der Skins mit sass schneller gehen wird und wir hier nochmal etwas Zeit raus holen.

Auch sollte man im Hinterkopf behalten, dass Instanzen mit großen Datenbeständen beim import auch mehr Zeit beanspruchen.

Ich schließe das Ticket, da der Vorschlad mit dem base image umgesetzt ist.

Gruß Daniel
