### ISSUE TITLE
Install container on other branches than master won't work

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#187]
dw@ubuntu:~/doiltests$ doil create -n tms73 -r tms -b r7.2 -p 7.3
Updating repository tms ... ok
Updating debian image ... ok
Starting mandatory doil services ... ok
Create basic folders ... ok
Setting folder permissions ... ok
Copying necessary files ... ok
Setting up configuration ... ok
Copying repository to target ...error: branch 'r7.2' not found.

**Comment by lauraherzog** [comment]
Might be fixed?
