### ISSUE TITLE
Saltify more scripts

### ISSUE THREAD

**Issue by catlauraherzog** [conceptsandtraining/doil#204]
It's possible to saltify even more scripts of doil:

* [ ] create
* [ ] proxy management (start, stop, prune, ...)
* [ ] mail system management (start, stop, ...)

**Comment by daniwe4** [comment]
Hallo @klees ,
weißt du was hiermit gemeint war?

**Comment by klees** [comment]
Ja! Zu dem Zeitpunkt, wo wir das Ticket geschrieben haben, wurden viele Vorgänge in doil per externem Shell-Script gesteuert. Da müsstest du ja auch viele von gefunden und auf PHP umgebaut haben.

Ziel ist generell, möglichst wenig Logik über interne Steuerung der Container in externen Skripten und  möglichst viel in Salt zu haben.

**Comment by daniwe4** [comment]
Vielen Dank.
Ich schließe das Ticket, da der Umbau zu PHP das meiste aufgeräumt haben sollte.
