### ISSUE TITLE
Roundcube-Config gegen Neustart resilient machen

### ISSUE THREAD

**Issue by klees** [conceptsandtraining/doil#207]
Es scheint so zu sein, dass die Config von Roundcube (insbesondere der Sieve-Filter) bei einem Neustart des Mailservers verschwindet. Das hat für nachvollziehbaren Unmut bei Florian gesorgt =)

**Comment by daniwe4** [comment]
Gibt es für die ordnerstruktur auch eine möglichkeit, die wieder zu importieren?
Kann man filterregeln irgendwie auch im nachhinein manuell anwenden?

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/260

**Comment by tbongers-cat** [comment]
Fixed in #260
