### ISSUE TITLE
WAC aktivieren

### ISSUE THREAD

**Issue by klees** [conceptsandtraining/doil#208]
Der ILIAS WebAccessChecker scheint aktuell bei Instanzen in doil nicht zu funktionieren.

Das sollte er aber =)

**Comment by daniwe4** [comment]
Hallo @klees ,

kannst du mir ein wenig mehr Infos geben. Was ist der ILIAS WebAccessChecker?

**Comment by klees** [comment]
Gerne!

* https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/configuration/secure.md#use-webaccesschecker
* https://docu.ilias.de/goto.php?target=wiki_1357_WAC%3A_Redesign_Web-Access-Checker

**Comment by daniwe4** [comment]
Ich lese aus den Artikeln, dass einfach nur das Apache-Rewite Modul aktiviert werden muss.

In base/apache/init.sls:

/etc/apache2/mods-enabled/rewrite.load:
  file.symlink:
    - target: /etc/apache2/mods-available/rewrite.load

**Comment by klees** [comment]
Jo, so könnte das sein =)

**Comment by daniwe4** [comment]
https://github.com/daniwe4/doil/pull/9
