### ISSUE TITLE
Diskrepanz supervisorctl und init.d

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#209]
Auf einem neu gestrateten doil_postfix Container laufen die Dienste postfix und dovecot nicht.
Der Versuch diese über supervisorctl zu starten endet in Error Meldungen.
Der Start über init.d funktioniert aber einwandfrei. Über ps aux bekomme ich die laufenden Dienste auch angezeigt.
Supervisorctl zeigt aber immer noch an, dass die Dienste nicht laufen.

**Comment by daniwe4** [comment]
Hier habe ich rausgefunden, dass das Problem wohl öfter autritt und wohl mit einer der nächsten dovecot Versionen behoben ist. Leider steht die momentan noch nicht für debian:stable bereit.

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/258

**Comment by tbongers-cat** [comment]
Fixed in #258
