### ISSUE TITLE
command-path into doil

### ISSUE THREAD

**Issue by nhaagen** [conceptsandtraining/doil#210]
With the basic assumption "work from outside a doil container" and "use doil to run things in " in mind, I would like to see a swift way to execute any command in a doil environment, i.e. the instance. 

The command should look something like doil exec [instance]  (-dir [desired path to run script in]) [command]  and accept any shell-line with an optional parameter to specify the directory the command will be executed in.
Output from the command should directly be piped back. 

This would probably make "doil login" obsolete for me, and fulfill a lot of other needs, like e.g. https://github.com/conceptsandtraining/doil/issues/126

Examples: 
`doil exec trunk -dir \var\www\html\setup "php setup.php update -y"`
or 
`doil exec trunk "mysql -A ilias"`

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/252

**Comment by tbongers-cat** [comment]
Added in #252
