### ISSUE TITLE
Compiling of single skin file

### ISSUE THREAD

**Issue by lukastocker** [conceptsandtraining/doil#212]
Currently it's not possible to compile a single skin file. Instead all files are compiled, which can take up some time and therefore is not feasible for development purposes.

Please include a possibility to choose and compile a single skin file. It also should be possible to exclude the source-map file during this process.

**Comment by daniwe4** [comment]
Abhängig von https://concepts-and-training.pixsoftware.de/jira/browse/TMS-7659

**Comment by daniwe4** [comment]
Der PR für cate steht https://github.com/conceptsandtraining/TMS6/pull/2216.
Danach sollte es kein Problem sein über das doil:exec Kommando einzelne Skins zu kompilieren.
