### ISSUE TITLE
Feature Request Docker-Desktop Support

### ISSUE THREAD

**Issue by kunzeus** [conceptsandtraining/doil#215]
Hello,

Foremost, praise to all you glorious people who save us the hassle of composer and outdated PHP versions management.

However, I'm mostly a console lazy person for more than installing packages. So I daily use Docker Desktop which is also available on Linux[1]. During testing the doil install script (Manjaro/Arch) I received the following errors:
```
~/Downloads/doil-master > sudo ./install.sh   
Checking requirements ... ok
Creating log file ... ok
Adding group ... ok
Creating mandatory folder ... ok
Copy doil system ... ok
Setting up basic configuration ... ok
Setting up IP ... ok
Setting up access rights ... ok
Configuring user specific data ... ok
Installing salt server .../usr/local/lib/doil/lib/system/salt/salt.sh: Zeile 84: docker-compose: Kommando nicht gefunden.
Error response from daemon: No such container: doil_saltmain
Error response from daemon: No such container: doil_saltmain
 ok
Installing proxy server ...Error: No such container: doil_saltmain
Error response from daemon: No such container: doil_proxy
Error response from daemon: No such container: doil_proxy
 ok
Installing mail server ...Error: No such container: doil_saltmain
Error response from daemon: No such container: doil_postfix
Error response from daemon: No such container: doil_postfix
 ok
[17.10.2022 12:44:52] Everything done
```

Probably one of the main differences in the Docker Desktop version is that: the composer plugin is already integrated in docker, and thereby the composer is called by "docker compose" [2]. As far as I can tell, it seems that the integration of the composer is supported by the docker developers [3] [4]. So, adapting to this change  would probably help future proof the project. 
I can't tell what else might be needed to achieve compatibility with the Docker Desktop environment. However, I would highly appreciate support for it.

[1] https://docs.docker.com/desktop/install/linux-install/ 
[2] https://docs.docker.com/compose/reference/
[3] https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command
[4] https://www.docker.com/blog/announcing-compose-v2-general-availability/

**Comment by daniwe4** [comment]
Hello Kunze,
Thanks for the hint. We are aware that this change from the Docker team may cause problems in doil. A short-term solution could be to additionally install the old docker-compose. If you try it, it would be nice if you share your experience with us here. For the future we already have plans to create an environment for doil in its own container so that we can better control the outside world. But until then, I hope we can find a workaround to avoid this problem.
Sincerely Daniel

**Comment by daniwe4** [comment]
Outdated.
