### ISSUE TITLE
install.sh/doil user:add should add user to docker group

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/doil#216]
Current behaviour:

After running `install.sh` or `doil user:add` doil might be unusable if the user isn't member of `docker`-group.

Expected behaviour:

User is added to `docker` group after running `install.sh`/`doil user:add`.

**Comment by daniwe4** [comment]
This should be handle by the admin before doil install or user add. There is a check now if the current user is not in doil/docker group.
I close this ticket.
