### ISSUE TITLE
Handling of command parameters

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/doil#218]
Current behaviour:

`doil instances:add -e test -b release_7` asks for instance name and release, if `-n` is not given as well.

Expected behaviour:

doil should only ask for parameters not given on command line (without specifying `-n`)

**Comment by daniwe4** [comment]
Ich denke, dass ich das Problem nicht lösen kann. Wir haben ja auch flags in der Parameterliste. Und bei denen kann ich nicht unterscheiden ob es absichtlich nicht gesetzt ist oder ob es einfach fehlt.
Man muß sich wohl an den -n Parameter gewöhnen.
Ich schliesse das Ticket.
