### ISSUE TITLE
Infinite loop on `Checking salt key ...`

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/doil#220]
Current:

`doil instances:create` run into an infinite loop checking the salt-key:

```
doil instances:create
[...]
Building minion image. This will take a while. Please be patient ... done
Checking salt key ...
```

Expected:

```
Checking salt key ... done
```

**Comment by daniwe4** [comment]
This depends on a missing requirement. So doil install should be updated to check all requirements.

**Comment by daniwe4** [comment]
https://github.com/daniwe4/doil/pull/2
