### ISSUE TITLE
install.sh should ask for hostname/IP

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/doil#225]
The default config assumes that the doil-server is reachable via `http://doil`. This is true for localhost, as the installer adds the IP of the nginx docker container to `/etc/hosts`.

Remote users have to add the name `doil` to their `/etc/hosts`-equivalents manually. This could be avoided, if the IP address instead of a hostname is used (or by using a registered DNS name).

Therefore the `install.sh` should as for the hostname/IP to be used.

**Comment by daniwe4** [comment]
https://github.com/daniwe4/doil/pull/3
