### ISSUE TITLE
`--prune` parameter for uninstall

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/doil#226]
Current:

`doil system:uninstall` removes any config file (e.g. `~/.doil`) and therefore all registered instances.

Expected:

`~/.doil` shouldn't be removed unless `--prune` is given. There should also be a warning, that `--prune` will remove the config-dirs of all doil users, not only the one uninstalling doil.

**Comment by tbongers-cat** [comment]
Fixed in #254
