### ISSUE TITLE
Readme is refering to outdated doil system:salt commands for troubleshooting

### ISSUE THREAD

**Issue by catenglaender** [conceptsandtraining/doil#236]
Some commands in the section Known Problems of the Readme should no longer refer to the old system command e.g. `doil system:salt prune` is now `doil salt:prune`
https://github.com/conceptsandtraining/doil#known-problems

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/239

**Comment by tbongers-cat** [comment]
Fixed in #239
