### ISSUE TITLE
Composer not executed during setup

### ISSUE THREAD

**Issue by tbongers-cat** [conceptsandtraining/doil#240]
Calling "_doil help_" after setup results in
`PHP Warning:  require_once(/usr/local/lib/doil/app/src/../vendor/autoload.php): Failed to open stream: No such file or directory`

Reason: While running ._setup/install.sh,_ composer was not executed for _/usr/local/lib/doil/app_ (Ubuntu 22.04.1).
After manually running "_composer install_", "_doil help_" was working fine.

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/246
