### ISSUE TITLE
X-Forwarded  header in ilias.ini.php

### ISSUE THREAD

**Issue by nhaagen** [conceptsandtraining/doil#242]
In einer neuen Instanz sind die Einträge in der ilias.ini auf "aus" gesetzt.
Wir brauchen für verschieden Issues aber bitte dieses:

[https]
auto_https_detect_enabled = "1"
auto_https_detect_header_name = "X-Forwarded-Proto"
auto_https_detect_header_value = "https"

**Comment by daniwe4** [comment]
Hi @nhaagen,
ich hab hier ein Problem. Wenn wir doil lokal nutzen brauchen wir die https-header nicht.
Mögliche Lösungen:
- ein weitere Flag am create command bspw. -s 
- doil ist nur https fähig (erfordert Zertifikate auch lokal)
- ein State, der im nachhinein die config änder und nochmal auf ILIAS anwendet (per setup/update)

Vieleicht fällt dir ja auch noch was ein. Ich bin sehr interessiert an deiner Meinung.
Aussedem interessiert mich noch die Meinung von @klees.

Gerne auch neue Vorschläge.

**Comment by daniwe4** [comment]
Evtl. muss hier auch der Proxy Eintrag direkt mit angepasst werden, damit er auf https weiter leitet.

**Comment by daniwe4** [comment]
Es gibt nun einen eigenen State, der den Proxy so anpasst, dass er https Anfragen entgegennimmt und per http an die ILIAS Instanzen weiterleitet. Dabei wird ein Header-Flag gesetzt.
Die ilias-config.json ist so angepasst, dass sie ILIAS anweisst https-autodetection zu benutzten.
Die Autodetection ließt das Header-Flag aus und schaltet HTTPS an.
Damit sollte dieses Ticket erledigt sein und wird geschloßen.
