### ISSUE TITLE
Installing php7.4-apcu fails

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#257]
Beim clonen einer Instanz ist aufgefallen, dass der State php7.4 fehlschlägt. Grund ist das fehlende PAcket php7.4-apcu. Vor der Installation sollte ein apt-update stattfinden.

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/259

**Comment by tbongers-cat** [comment]
Fixed in #259
