### ISSUE TITLE
Add an option for setting roundcube password on instance creation

### ISSUE THREAD

**Issue by tbongers-cat** [conceptsandtraining/doil#267]
Please add an option to set the roundcube password on instance creation (not just afterwards via the newly added command in feature release).

**Comment by daniwe4** [comment]
Hi @tbongers-cat ,
i think roundcube password isnt't somethig that is instance specific. Perhaps it should take place in the setup script.
Whats your opinion?

**Comment by tbongers-cat** [comment]
Indeed, that is a better option. Make it so!

**Comment by daniwe4** [comment]
https://github.com/conceptsandtraining/doil/pull/276

**Comment by tbongers-cat** [comment]
Added in #276
