### ISSUE TITLE
Vor dem löschen eines Users alte instanzen löschen

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#288]
Bevor ein user gelöscht wird sollte eine Abfrage sicherstellen, dass der Ausführende alle Instanzen des zu löschenden User gestoppt und gelöscht hat.
Nachdem der User gelöscht wurde besteht keine Möglichkeit mehr über doil auf die Instanzen zuzugreifen.

**Comment by tbongers-cat** [comment]
Added in #289
