### ISSUE TITLE
Readme ergänzen um kurze doil pack-Beschreibung und Verweis auf die --hilfe

### ISSUE THREAD

**Issue by catkrahl** [conceptsandtraining/doil#328]

**Comment by daniwe4** [comment]
Ausserdem, sollte eine Beschreibung mit rein, was zu tun ist wenn eine Instanz nicht sauber installiert wurde.

**Comment by daniwe4** [comment]
Ich finde die doil Dokumentation mittlerweile sehr unübersichtlich. Ich schiebe dieses Ticket deswegen in einen neuen Milestone.
Der neue Milestone soll sich expliziet um die Doil Doku kümmern.

**Comment by daniwe4** [comment]
Move README into github WIKI
