### ISSUE TITLE
Update of repo does not remove deleted branches.

### ISSUE THREAD

**Issue by dsstrassner** [conceptsandtraining/doil#370]
I have deleted old branches on my [GH-repo](https://github.com/dsstrassner/ILIAS/branches/yours) and updated doil. But the old branches are still in the list, when I create a new doil instances. (Remark: I use ssh for this repo). See: 

![image](https://github.com/conceptsandtraining/doil/assets/66684170/e4bf7ed4-21d1-4994-b301-8936187f7a96)

Repo: 

![image](https://github.com/conceptsandtraining/doil/assets/66684170/d6999ebc-f166-46eb-aad1-06b02a60ce52)

The old branches should also vanish in doil or do I miss something?

**Comment by tbongers-cat** [comment]
Fixed in #376
