### ISSUE TITLE
Detected dubios ownership in repo during doil create

### ISSUE THREAD

**Issue by lukastocker** [conceptsandtraining/doil#371]
Even after running the recommended command "git config --global --add safe.directory /usr/local/share/doil/repositories/master_import" I can't create a instance with doil because the repo's ownership isn't aligned with my user. 

![doil issue - dubios ownership](https://github.com/conceptsandtraining/doil/assets/67695434/564ca2d4-4fb7-4669-92e7-d9f3248ae6cb)

**Comment by tbongers-cat** [comment]
Fixed in #379
