### ISSUE TITLE
Doil pack:import - no such file: docker-compose.yml

### ISSUE THREAD

**Issue by lukastocker** [conceptsandtraining/doil#372]
While trying to import an exported instance (a new instance wasn't created beforehand) I get the error message, that the file/directory 'usr/local/share/doil/isntances/INSTANCENAME/docker-compose.yml' does not exist.

![issue_doil](https://github.com/conceptsandtraining/doil/assets/67695434/eed14b01-2559-405e-bbe4-d65c0e03fcac)

**Comment by daniwe4** [comment]
Should be resolved by https://github.com/conceptsandtraining/doil/pull/380
