### ISSUE TITLE
Permission denied (publickey) - Could not read remote repo

### ISSUE THREAD

**Issue by lukastocker** [conceptsandtraining/doil#373]
While trying to create a new instance I get no permission to access the remote repository even being part of the needed groups.

![doil - perm. denied - repository](https://github.com/conceptsandtraining/doil/assets/67695434/bf84e12c-4d4a-4aef-a21d-ebc7760ac7c6)

**Comment by daniwe4** [comment]
Das sollte kein Problem sein wenn der Nutzer richtig eingerichtet ist.
Dann sollte es eh nicht nötig sein, dass root Konto zu nutzen.
Ich schließe das Ticket.
