### ISSUE TITLE
Doil create: bind src path does not exist

### ISSUE THREAD

**Issue by lukastocker** [conceptsandtraining/doil#374]
When trying to create a new instance with my user I get the message, that the bind path does not exist. After creating that path the error didn't appear anymore.

![doil - bind path not existing](https://github.com/conceptsandtraining/doil/assets/67695434/00897307-1496-40e2-a0f7-50a6791ddff6)

**Comment by daniwe4** [comment]
Double of https://github.com/conceptsandtraining/doil/issues/367
I close this ticket.
