### ISSUE TITLE
Doil up, down etc. not possible after pack:import (global) 

### ISSUE THREAD

**Issue by lukastocker** [conceptsandtraining/doil#375]
I created (as my user - not root) a global instance and wanted to import an export zip file, which was also created as global. But suddenly there was a folder named like "._8Zy" with all the needed directories and files from ilias like volumes, ilias, data etc. The created instance name wasn't there anymore. Doil up, down, etc. wasn't possible anymore. Docker ps -a and images showed, that the instance still exists though.

**Comment by daniwe4** [comment]
doil pack:import checken, ob es die Instanz mit root rechten löschen muß oder ob die Instanz überhaupt gelöscht wird

**Comment by tbongers-cat** [comment]
Fixed in #380
