### ISSUE TITLE
Deprecation warning during update for version 20230919

### ISSUE THREAD

**Issue by tbongers-cat** [conceptsandtraining/doil#389]
On a current Ubuntu 22.04 system, the following deprecation warning is shown while the PHP image is built:

*Building doil php image ...DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/*

**Comment by daniwe4** [comment]
Evtl. muss hier noch ein check beim installieren/updaten von doil rein.
Wird im nächsten Release implementiert.
