### ISSUE TITLE
doil can't be called from cron

### ISSUE THREAD

**Issue by daniwe4** [conceptsandtraining/doil#392]
Wenn doil über cron ausgeführt wird, kommt es zu einem Fehler:

TTY mode requires /dev/tty to be read/writable.

Das liegt daran, dass Doil einen TTY Aufruf macht um Ausgaben auf der Konsole zu tätigen. Cron stellt aber kein TTY zur verfügung.
Um doil cronable zu machen muss die Aufrufkette in doil so angepasst werden, dass sie auch ohne TTY klar kommt.
Dafür sollte ein Schalter -c / --cron zum entsprechenden doil Befehl hinzugefügt werden (in diesem Fall doil:pack export).

**Comment by tbongers-cat** [comment]
Fixed in #398
