### ISSUE TITLE
doil Instanzen werden teilweise in der Übersicht nicht geführt

### ISSUE THREAD

**Issue by dsstrassner** [conceptsandtraining/doil#435]
Ich betreibe doil seit kurzem auf meinem Macbook Pro M2 in einem virtualisierten Ubuntu 22.01 Server (VMWare Fusion). Alles unter ARM-Architektur. doil funktioniert größtenteils gut. Nur muss bei jedem neuen Create oder bevor eine Instanz hochgefahren wird, muss nach einem Reboot 

`sudo chown "$USER":"$USER" /home/"$USER"/.docker -R ` und 

`sudo chmod g+rwx "$HOME/.docker" -R ` ausgeführt werden, damit Doil die Instanzen auch weitergibt, d.h. sie nach dem doil up auch in der Übersicht der Instanzen auftauchen und zugreifbar sind. 
Docker wurde entsprechend der Anleitung auf docker.com Installiert.

Ansonsten sieht es so aus: 

![image](https://github.com/conceptsandtraining/doil/assets/66684170/eb384304-426a-4890-84c4-07ad2a51538c)
![image](https://github.com/conceptsandtraining/doil/assets/66684170/46e74583-d083-42c1-91df-909f01a6cf49)

Issue auf Wunsch von @klees erstellt. Sorry, keine Energie mehr für Englisch gehabt.

**Comment by daniwe4** [comment]
Hi @dsstrassner ,

Deutsch ist hier auch völlig ok.

Für mich sieht das nicht nach einem Problem aus, dass doil verursacht. Du berichtest, dass das nach jedem Reboot passiert. Gibt es in deiner VM einen automatismus, der diese Aktionen auf den .docker Ordner ausführt?

Interessant wäre noch zu wissen ob das nach jedem Reboot passiert, oder nur einmalig?

Eine Quick und Dirty Lösung könnte sein, ein Startup Script zu hinterlegen, welches den Ordner nach deine Wünschen anpasst.

**Comment by klees** [comment]
Hallo @daniwe4,

vllt. macht es Sinn, das wenigstens als Known-Issue in der Readme aufzunehmen.

Viele Grüße!

**Comment by daniwe4** [comment]
Hallo @klees ,

mach ich gerne. Aber wir sollten vorher klären warum das genau passiert.

**Comment by dsstrassner** [comment]
Ja, nach jedem Reboot. Ich reboote, ich starte die Instanz, die Übersicht und die Instanz ist nicht erreichbar, obwohl der Status sagt, dass sie oben sind. Ich führe die 2 Befehle aus und ich kann dann wieder auf die Übersicht und die hochgefahrene Instanz zugreifen.
Ich habe nichts besonderes eingerichtet, die was in .docker tun sollte. Ich habe "einfach" nur installiert, docker nach Anleitung installiert und danach doil installiert.

**Comment by daniwe4** [comment]
Da es sich hier um das von docker erstellte Verzeichnis ~/.docker handelt und der doil code dieses Verzeichnis nicht behandelt schließe ich dieses Ticket.
Unsere Vermutung ist, dass es entweder mit dem Betriebssystem oder mit VMware Fusion  zu tun hat.
@klees, da mir das sehr nach einem Fall aussieht, der nur selten vorkommt möchte ich das lieber nicht mit in die README aufnehmen. Die ist eh schon sehr voll gepackt.

**Comment by klees** [comment]
Packs rein bitte. Ich hoffe Denis wird nicht der letzte gewesen sein, der dass auf seinem Mac findet.

**Comment by daniwe4** [comment]
Hallo @klees ,

ich habs hinzugefügt https://github.com/conceptsandtraining/doil/pull/436
