### ISSUE TITLE
SAML-IdP in doil einbinden und an Instanzen anbinden

### ISSUE THREAD

**Issue by klees** [conceptsandtraining/doil#449]
TBD

**Comment by daniwe4** [comment]
Doil soll einen IdP zur Verfügung stellen. Über diesen sollen dann die Logins auf die ILIAS Instanzen ausgeführt werden.
Der Zugriff auf diesen IdP soll über den cat-office IdP geregelt werden.

Der Doil eigene IdP soll in einem seperaten Container betrieben werden. 
Implemtiert werden soll er entweder über PHP-SAML oder über Keycloak. Evtl. gibt es da bereits Images auf Dockerhub.
