### ISSUE TITLE
permissions/directories

### ISSUE THREAD

**Issue by nhaagen** [conceptsandtraining/doil#62]
Ich muss die Schreibrechte für Logfiles manuell setzen. 
Außerdem muss ich mehrere Verzeichnisse anlegen.
Ich bin mir unsicher, ob das ein doil-Thema ist oder in die ILIAS-Installation gehört. vermutlich beides.

z.B. muss ich derzeit anlegen:
- data/ilias/temp
- data/ilias/mail
- data/ilias/pwsalt.txt (touch)

**Comment by lauraherzog** [comment]
@nhaagen Please check if this is still a problem in 1.2.

**Comment by lauraherzog** [comment]
Das Problem existiert in 1.2 nicht mehr. Daher close.
